services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: song-vault-next
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - song-vault-net
    
  db:
    image: postgres:16
    container_name: song-vault-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: song-vault
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - song-vault-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: song-vault-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - song-vault-net

volumes:
  postgres_data:

networks:
  song-vault-net: